dashboard/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # post 'wallet/use'

  scope module: :admin, path: '/admin' do
    root to: 'pairs#index'
    resources :pairs, only: %i[index new edit create update destroy]
    resources :posts, only: %i[index]
    get 'preview', to: 'previews#show'
  end

  namespace :api, constraints: { ip: /127\.0\.0\.1/ } do
    resource :events, only: %i[create]
  end

  scope :soon do
    # get 'landing', to: 'home#show', page: :landing
    # resource :push_devices, only: %i[show create destroy]
  end

  root to: 'home#index'
end

dashboard/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dashboard/app/models/pair.rb
# frozen_string_literal: true

class Pair < ApplicationRecord
  has_many :reports, dependent: :restrict_with_error

  validates :symbol, presence: true, uniqueness: true, format: /\A[A-Z0-9]+\z/
  validates :name, presence: true

  def self.find_matching(val)
    where('symbol LIKE ?', "#{val.upcase}%").first!
  end

  def tags=(val)
    val.is_a?(Array) ? super : super(val&.split)
  end
end

dashboard/app/models/push_device.rb
# frozen_string_literal: true

class PushDevice < ApplicationRecord
  validates :endpoint, presence: true, uniqueness: true

  def keys=(val)
    assign_attributes(val.slice(:p256dh, :auth))
  end
end

dashboard/app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  include ImageUploader[:image]

  belongs_to :pair

  validates :limit, numericality: true, inclusion: { in: 80..200 }
  validates :timeframe, presence: true, inclusion: { in: [1, 2, 3, 6, 12, 24].freeze }
  validates :indicators, presence: true
  validates :comment, presence: true
  validates :image, presence: true
end

dashboard/app/models/twitter_post.rb
# frozen_string_literal: true

class TwitterPost < ApplicationRecord
  scope :published, -> { where.not(published_at: nil) }

  belongs_to :report, optional: true

  validates :in_reply_to, presence: true, uniqueness: true
end

dashboard/app/models/wallet.rb
# frozen_string_literal: true

class Wallet < ApplicationRecord
  def address
    @address ||= BtcWallet.new(id).derive
  end
end

dashboard/app/controllers/admin/admin_controller.rb
# frozen_string_literal: true

module Admin
  class AdminController < ApplicationController
    http_basic_authenticate_with name: Settings.admin_panel.login,
                                 password: Settings.admin_panel.password

    layout 'admin'
  end
end

dashboard/app/controllers/admin/pairs_controller.rb
# frozen_string_literal: true

module Admin
  class PairsController < AdminController
    def index
      @pairs = Pair.order(symbol: :asc)
    end

    def new
      @pair = Pair.new
    end

    def edit
      @pair = pair
    end

    def create
      @pair = Pairs::Creator.new(symbol: pair_params[:symbol],
                                 name: pair_params[:name],
                                 tags: pair_params[:tags]).call

      redirect_to pairs_path, notice: "#{@pair.symbol} created"
    rescue Service::ValidationError => e
      @pair = Pair.new(pair_params)
      @pair.errors.add(:base, e.message)
      render :new
    end

    def update
      if pair.update(pair_params)
        redirect_to pairs_path, notice: "#{@pair.symbol} updated"
      else
        render :edit
      end
    end

    def destroy
      pair.destroy!
      redirect_to pairs_path, notice: 'Pair destroyed.'
    end

    private

    def pair
      @pair ||= Pair.find(params[:id])
    end

    def pair_params
      params.require(:pair).permit(:symbol, :name, :tags)
    end
  end
end

dashboard/app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

module Admin
  class PostsController < AdminController
    include Pagy::Backend

    def index
      @pagy, @posts = pagy(TwitterPost.includes(report: [:pair]).order(published_at: :desc),
                           items: 10)
    end
  end
end

dashboard/app/controllers/admin/previews_controller.rb
# frozen_string_literal: true

module Admin
  class PreviewsController < AdminController
    def show
      timeframe = params[:timeframe] || 6
      indicators = (params[:indicators] || 'RSI,wedge,double_top,double_bottom,levels').split(',')
      report = Reports::Creator.new(pair: pair,
                                    timeframe: timeframe,
                                    indicators: indicators).call
      send_data(report.image[:original].read, disposition: 'inline', type: 'image/png')
    end

    private

    def pair
      @pair ||= Pairs::Finder.new(symbol: params[:symbol]).call
    end
  end
end

dashboard/app/controllers/api/api_controller.rb
# frozen_string_literal: true

module Api
  class ApiController < ApplicationController
    skip_before_action :verify_authenticity_token

    # respond_to :json
  end
end

dashboard/app/controllers/api/events_controller.rb
# frozen_string_literal: true

module Api
  class EventsController < ApiController
    # POST /api/events
    def create
      PushDevice.find_each do |push|
        Webpush.payload_send(
          message: 'Notification',
          endpoint: push.endpoint,
          p256dh: push.p256dh,
          auth: push.auth,
          vapid: {
            public_key: Settings.push.vapid.public_key,
            private_key: Settings.push.vapid.private_key,
            expiration: 12 * 60 * 60
          }
        )
      end
    end
  end
end

dashboard/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_raven_context
  protect_from_forgery with: :exception

  private

  def set_raven_context
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

dashboard/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def show
    @address = session[:address] ||= initialize_wallet.address
    render params[:page]
  end

  private

  def initialize_wallet
    wallet = Wallet.create
    session[:wallet_id] = wallet.id
    wallet
  end
end

dashboard/app/controllers/push_devices_controller.rb
# frozen_string_literal: true

class PushDevicesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[create destroy]

  def show
    render 'show'
  end

  def create
    PushDevice.create(push_device_params)
  end

  def destroy
    pd = PushDevice.find_by(endpoint: params[:subscription][:endpoint])
    pd&.destroy
  end

  private

  def push_device_params
    params.require(:subscription).permit(:endpoint, keys: %i[p256dh auth])
  end
end

dashboard/app/controllers/wallet_controller.rb
# frozen_string_literal: true

class WalletController < ApplicationController
  def use
    wallet = Wallet.find(session[:wallet_id])
    wallet&.update(used: true)
    head :ok
  end
end

dashboard/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

dashboard/app/views/admin/pairs/_form.html.slim
= form_for @pair, html: {class: 'ui form'} do |f|
  - if @pair.errors.any?
    #error_explanation
      h2 = "#{pluralize(@pair.errors.count, 'error')} prohibited this pair from being saved:"
      ul
        - @pair.errors.full_messages.each do |message|
          li = message

  .ui.segment
    h4.ui.dividing.header Pair Settings
    .four.fields
      .required.field
        = f.label :symbol
        = f.text_field :symbol, { prompt: 'Select currency pair' }
      .field
        = f.label :name
        = f.text_field :name
      .field
        = f.label :tags, 'Tags (space separated)'
        = f.text_field :tags, { prompt: '$BTC #bitcoin #btc' }
    h4.ui.dividing.header Actions
    = f.button :submit, class: 'ui green right labeled icon button' do
      i.right.arrow.icon
      | Save

dashboard/app/views/admin/pairs/edit.html.slim
.ui.padded.basic.segment
  h1 = "Edit pair #{@pair.symbol}"

  = render 'form'

  .ui.basic.segment
    = link_to pairs_path do
      .ui.labeled.icon.button
        i.arrow.left.icon
        | Back

dashboard/app/views/admin/pairs/index.html.slim
h1 Listing pairs

table.ui.celled.table
  thead
    tr
      th Symbol
      th Name
      th Tags
      th Actions
  tbody
    - @pairs.each do |pair|
      tr
        td= pair.symbol
        td= pair.name
        td= Array.wrap(pair.tags).join(' ')
        td.collapsing
          .ui.buttons.vertical
            = link_to edit_pair_path(pair) do
              .ui.button
                i.pencil.icon
                | Edit
            = link_to pair, data: { confirm: 'Are you sure?' }, method: :delete do
              .ui.button
                i.red.delete.icon
                | Delete

= link_to new_pair_path do
  .ui.green.button
    i.exchange.icon
    | New pair

dashboard/app/views/admin/pairs/new.html.slim
.ui.padded.basic.segment
  h1 New pair

  = render 'form'

  .ui.basic.segment
    = link_to pairs_path do
      .ui.labeled.icon.button
        i.arrow.left.icon
        | Back

dashboard/app/views/admin/posts/index.html.slim
h1 Published Twitter Posts

table.ui.celled.table
  thead
    tr
      th Pair
      th Preview
      th Original Message
      th Response
      th Publish date
      th Actions
  tbody
    - @posts.each do |post|
      tr
        / :<
        td= post.report&.pair&.symbol
        td
          - if post.report
            = link_to post.report.image_url(:original) do
              = image_tag(post.report.image_url(:thumbnail))
          - else
            p 🤷
        td= post.original_message
        td= post.message
        td= post.published_at
        td.collapsing
          .ui.buttons.vertical
            = link_to "https://twitter.com/statuses/#{post.tweet_id}" do
              .ui.button
                i.eye.icon
                | See Tweet
            = link_to '#' do
              .ui.disabled.button
                i.delete.icon
                | Delete

== pagy_semantic_nav(@pagy)

dashboard/app/views/home/_menu.html.slim
- if main_menu
  .logo.item
    = image_tag "logo#{logo}", class: 'ui image'
  .right.menu
    = render 'menu_right'
    a.toc.item.mobile.only
      i.sidebar.icon

dashboard/app/views/home/_menu_right.html.slim
a.ui.features.item Features
a.ui.contact.item Contact
a.ui.cta.item
  strong Early Access

dashboard/app/views/home/index.html.slim
.ui.basic.yellow.center.aligned.segment
  h1 Comming soon
  = link_to 'bitReport.org', root_path, class: 'ui black button'
  = link_to 'https://twitter.com/Bitreport_org' do
    .ui.blue.button
      i.twitter.icon
      | @Bitreport_org

dashboard/app/views/home/landing.html.slim
/! Donation Modal
.ui.small.donation.modal
  i.black.close.icon
  .ui.icon.header Join Early Access
  .content.center.aligned
    p The first private Beta is almost ready. Support the project and be the first to get access to all features. No minimum amount, buy us a coffee and we're good to go!
    .ui.left.action.right.labeled.fluid.input
      a.ui.yellow.labeled.icon.button href="bitcoin:#{@address}"
        i.bitcoin.icon
        | Pay with BTC
      input type="text" value=@address readonly="readonly" autofocus="true" title="wallet address"
      .ui.button.qr.label data-position="top right"
        i.qrcode.large.black.icon
      .ui.popup
        canvas#address.ui.fluid.image style='border: 0;' data-address=@address
    .ui.horizontal.divider Note
    p
      small Keep above address for later, as it will become your unique Early Access code. Follow us on Facebook and Twitter to be notified when the Early Access begins.
  .actions
    a.ui.tiny.compact.basic.disabled.button
      | Find us on:
    a.ui.tiny.compact.twitter.icon.button href="https://twitter.com/Bitreport_org" target="_blank"
      i.twitter.icon
    a.ui.tiny.compact.facebook.icon.button href="https://www.facebook.com/bitreport.org/" target="_blank"
      i.facebook.icon

/! Following Menu
.ui.secondary.pointing.top.fixed.hidden.main.menu
  .ui.text.container
    = render 'menu', main_menu: true, logo: '_white'

/! Sidebar Menu
.ui.simple.sidebar.inverted.vertical.menu
  = render 'menu_right'

/! Page Contents
.pusher
  .ui.vertical.masthead.segment
    .ui.text.container
      .ui.secondary.main.menu
        = render 'menu', main_menu: true, logo: ''
    .ui.middle.aligned.stackable.grid.text.container
      .row
        .eight.wide.column
          .ui.container
            h1 Let's bull together
            p Best way to start your journey with cryptocurrencies and technical analysis
            p
              small Making money on exchange requires knowledge. We have learnt it losing our money first. Inspired by this experience we decide to create simple but powerful reports. We mix classical indicators with automated pattern recognition never available before.
            button.ui.black.cta.button Join Now
        .one.wide.iphone.column.no.mobile
        .seven.wide.iphone.column.no.mobile
          .ui.instant.fade.reveal.image
            = image_tag 'iphone_screen1', class: 'visible content'
            = image_tag 'iphone_screen2', class: 'hidden content'

  .ui.vertical.stripe.description.segment
    .ui.center.aligned.text.container
      h2 bitReport features
      p
        | Beginner and occasional traders have a lot to learn before becoming experts.
        br
        | With bitReport their journey becomes easier from the beginning.
      button.ui.fade.animated.basic.features.button
        .visible.content See all features
        .hidden.content
          i.down.arrow.icon

  .ui.vertical.stripe.features.segment
    .ui.three.column.equal.height.stackable.grid.container
      .column
        .ui.grid.container
          .two.wide.column
            i.large.empty.star.icon
          .fourteen.wide.column
            h3 Classic Indicators
            p You can make use of a wide selection of classic trading indicators. RSI, MACD, EMA? We've got them all!
      .column
        .ui.grid.container
          .two.wide.column
            i.large.line.chart.icon
          .fourteen.wide.column
            h3 Elliot Waves
            p Thanks to advanced machine learning algorithms we let you quickly spot new trends based on Elliot Wave Theory.
      .column
        .ui.grid.container
          .two.wide.column
            i.large.sidebar.icon
          .fourteen.wide.column
            h3 Automated Levels
            p Wondering when to take profit? With our support and resistance recognition you can easily spot reversal zones.
      .column
        .ui.grid.container
          .two.wide.column
            i.large.exchange.icon
          .fourteen.wide.column
            h3 Cutting Edge Technology
            p To be successful you have to be faster than others. We achieve this with cutting edge machine learning algorithms.
      .column
        .ui.grid.container
          .two.wide.column
            i.large.mail.outline.icon
          .fourteen.wide.column
            h3 Instant Notifications
            p Never miss a trade opportuninty with instant notifications and customizable email reports.
      .column
        .ui.grid.container
          .two.wide.column
            i.large.remove.bookmark.icon
          .fourteen.wide.column
            h3 Free Forever
            p You can use bitReport for free as long as you like. No payment required.

  .ui.inverted.vertical.footer.segment
    .ui.center.aligned.inverted.equal.height.stackable.mobile.reversed.grid.text.container
      .four.wide.column
        h4.ui.inverted.header About
        .ui.inverted.link.list
          a.item Sitemap
          a.item Contact Us
          a.item Stuff
      .four.wide.column
        h4.ui.inverted.header Services
        .ui.inverted.link.list
          a.item Pre-Order
          a.item FAQ
          a.item Pricing
      .eight.wide.column
        h4.ui.inverted.header
          | Support the project and gain
          br
          | Early Access with unique features
        button.ui.yellow.labeled.icon.cta.button
          i.bitcoin.icon
          | Support this project

dashboard/app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport"
    title Admin Dashboard
    = csrf_meta_tags
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'admin', 'data-turbolinks-track': 'reload'
  body class="#{controller_name} #{action_name}"
    .ui.container
      p.notice = notice
      p.alert = alert
      = yield
      .ui.segment
        = link_to pairs_path do
          .ui.button
            i.cogs.icon
            | Pairs management
        = link_to posts_path do
            .ui.button
              i.twitter.icon
              | Published posts

dashboard/app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport"
    title Dashboard
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link rel="manifest" href="/manifest.json"
  body class="#{controller_name} #{action_name}"
    = yield
    = render 'shared/clickdesk'

dashboard/app/views/push_devices/show.html.slim
.ui.basic.yellow.center.aligned.segment
  h1 Subscribe here:
  button.ui.black.button#subscribe(disabled) Magic subscribe button

dashboard/app/views/shared/_clickdesk.html.slim
- if Rails.env.production?
  javascript:
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"),
            s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/5c39239b494cc76b7872b55d/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();